// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v4.24.4
// source: proto/locator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameObjectMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guid          uint32                 `protobuf:"varint,1,opt,name=guid,proto3" json:"guid,omitempty"`
	Sid           int32                  `protobuf:"varint,2,opt,name=sid,proto3" json:"sid,omitempty"`
	X             float32                `protobuf:"fixed32,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,4,opt,name=y,proto3" json:"y,omitempty"`
	W             float32                `protobuf:"fixed32,5,opt,name=w,proto3" json:"w,omitempty"`
	H             float32                `protobuf:"fixed32,6,opt,name=h,proto3" json:"h,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameObjectMsg) Reset() {
	*x = GameObjectMsg{}
	mi := &file_proto_locator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameObjectMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameObjectMsg) ProtoMessage() {}

func (x *GameObjectMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_locator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameObjectMsg.ProtoReflect.Descriptor instead.
func (*GameObjectMsg) Descriptor() ([]byte, []int) {
	return file_proto_locator_proto_rawDescGZIP(), []int{0}
}

func (x *GameObjectMsg) GetGuid() uint32 {
	if x != nil {
		return x.Guid
	}
	return 0
}

func (x *GameObjectMsg) GetSid() int32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *GameObjectMsg) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *GameObjectMsg) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *GameObjectMsg) GetW() float32 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *GameObjectMsg) GetH() float32 {
	if x != nil {
		return x.H
	}
	return 0
}

type MatchMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guid          uint32                 `protobuf:"varint,1,opt,name=guid,proto3" json:"guid,omitempty"`
	Sid           int32                  `protobuf:"varint,2,opt,name=sid,proto3" json:"sid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchMsg) Reset() {
	*x = MatchMsg{}
	mi := &file_proto_locator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchMsg) ProtoMessage() {}

func (x *MatchMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_locator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchMsg.ProtoReflect.Descriptor instead.
func (*MatchMsg) Descriptor() ([]byte, []int) {
	return file_proto_locator_proto_rawDescGZIP(), []int{1}
}

func (x *MatchMsg) GetGuid() uint32 {
	if x != nil {
		return x.Guid
	}
	return 0
}

func (x *MatchMsg) GetSid() int32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

type StorableMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameObject    *GameObjectMsg         `protobuf:"bytes,1,opt,name=game_object,json=gameObject,proto3" json:"game_object,omitempty"`
	Ttl           int64                  `protobuf:"varint,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorableMsg) Reset() {
	*x = StorableMsg{}
	mi := &file_proto_locator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorableMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorableMsg) ProtoMessage() {}

func (x *StorableMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_locator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorableMsg.ProtoReflect.Descriptor instead.
func (*StorableMsg) Descriptor() ([]byte, []int) {
	return file_proto_locator_proto_rawDescGZIP(), []int{2}
}

func (x *StorableMsg) GetGameObject() *GameObjectMsg {
	if x != nil {
		return x.GameObject
	}
	return nil
}

func (x *StorableMsg) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*StorableMsg         `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_locator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_locator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_locator_proto_rawDescGZIP(), []int{3}
}

func (x *SubscribeRequest) GetSubscriptions() []*StorableMsg {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Publications  []*StorableMsg         `protobuf:"bytes,1,rep,name=publications,proto3" json:"publications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_proto_locator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_locator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_proto_locator_proto_rawDescGZIP(), []int{4}
}

func (x *PublishRequest) GetPublications() []*StorableMsg {
	if x != nil {
		return x.Publications
	}
	return nil
}

type SubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Publications  []*MatchMsg            `protobuf:"bytes,1,rep,name=publications,proto3" json:"publications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_proto_locator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_locator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_proto_locator_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribeResponse) GetPublications() []*MatchMsg {
	if x != nil {
		return x.Publications
	}
	return nil
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_proto_locator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_locator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_proto_locator_proto_rawDescGZIP(), []int{6}
}

var File_proto_locator_proto protoreflect.FileDescriptor

var file_proto_locator_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x6d,
	0x0a, 0x0d, 0x47, 0x61, 0x6d, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x73, 0x67, 0x12,
	0x12, 0x0a, 0x04, 0x67, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x67,
	0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01,
	0x79, 0x12, 0x0c, 0x0a, 0x01, 0x77, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x77, 0x12,
	0x0c, 0x0a, 0x01, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x68, 0x22, 0x30, 0x0a,
	0x08, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x67, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x73, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x69, 0x64, 0x22,
	0x58, 0x0a, 0x0b, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x37,
	0x0a, 0x0b, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x47, 0x61,
	0x6d, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x73, 0x67, 0x52, 0x0a, 0x67, 0x61, 0x6d,
	0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x74, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x74, 0x74, 0x6c, 0x22, 0x4e, 0x0a, 0x10, 0x53, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a,
	0x0d, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x53,
	0x74, 0x6f, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x4d, 0x73, 0x67, 0x52, 0x0d, 0x73, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x4a, 0x0a, 0x0e, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x0c, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x53, 0x74, 0x6f, 0x72,
	0x61, 0x62, 0x6c, 0x65, 0x4d, 0x73, 0x67, 0x52, 0x0c, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x4a, 0x0a, 0x11, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0c, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68,
	0x4d, 0x73, 0x67, 0x52, 0x0c, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x22, 0x11, 0x0a, 0x0f, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0x8b, 0x01, 0x0a, 0x07, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x6f, 0x72,
	0x12, 0x42, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x19, 0x2e,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x6f, 0x72, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x07, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x12,
	0x17, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x6f, 0x72, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x27, 0x5a, 0x25, 0x63, 0x73, 0x34, 0x32, 0x36, 0x2e, 0x79, 0x61, 0x6c, 0x65,
	0x2e, 0x65, 0x64, 0x75, 0x2f, 0x63, 0x6f, 0x6c, 0x79, 0x73, 0x65, 0x75, 0x73, 0x2f, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_locator_proto_rawDescOnce sync.Once
	file_proto_locator_proto_rawDescData = file_proto_locator_proto_rawDesc
)

func file_proto_locator_proto_rawDescGZIP() []byte {
	file_proto_locator_proto_rawDescOnce.Do(func() {
		file_proto_locator_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_locator_proto_rawDescData)
	})
	return file_proto_locator_proto_rawDescData
}

var file_proto_locator_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_locator_proto_goTypes = []any{
	(*GameObjectMsg)(nil),     // 0: locator.GameObjectMsg
	(*MatchMsg)(nil),          // 1: locator.MatchMsg
	(*StorableMsg)(nil),       // 2: locator.StorableMsg
	(*SubscribeRequest)(nil),  // 3: locator.SubscribeRequest
	(*PublishRequest)(nil),    // 4: locator.PublishRequest
	(*SubscribeResponse)(nil), // 5: locator.SubscribeResponse
	(*PublishResponse)(nil),   // 6: locator.PublishResponse
}
var file_proto_locator_proto_depIdxs = []int32{
	0, // 0: locator.StorableMsg.game_object:type_name -> locator.GameObjectMsg
	2, // 1: locator.SubscribeRequest.subscriptions:type_name -> locator.StorableMsg
	2, // 2: locator.PublishRequest.publications:type_name -> locator.StorableMsg
	1, // 3: locator.SubscribeResponse.publications:type_name -> locator.MatchMsg
	3, // 4: locator.Locator.Subscribe:input_type -> locator.SubscribeRequest
	4, // 5: locator.Locator.Publish:input_type -> locator.PublishRequest
	5, // 6: locator.Locator.Subscribe:output_type -> locator.SubscribeResponse
	6, // 7: locator.Locator.Publish:output_type -> locator.PublishResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_locator_proto_init() }
func file_proto_locator_proto_init() {
	if File_proto_locator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_locator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_locator_proto_goTypes,
		DependencyIndexes: file_proto_locator_proto_depIdxs,
		MessageInfos:      file_proto_locator_proto_msgTypes,
	}.Build()
	File_proto_locator_proto = out.File
	file_proto_locator_proto_rawDesc = nil
	file_proto_locator_proto_goTypes = nil
	file_proto_locator_proto_depIdxs = nil
}
